baseurl: /dev-environment
markdown: redcarpet
name: 18F Development Environment Guide [DRAFT]
exclude:
- go
- copy-template
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md

permalink: pretty
highlighter: rouge

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: People not Systems
  url: people/
  internal: true
- text: Self Provisioning
  url: self-provisioning/
  internal: true
- text: Automation
  url: automation/
  internal: true
- text: Environments 
  url: environments/
  internal: true
- text: Updates
  url: updates/
  internal: true
- text: Build Promotion
  url: build-promotion/
  internal: true
- text: Service Contracts
  url: service-contracts/
  internal: true

repos:
- name: Development Environment
  description: Main repository
  url: https://github.com/18F/dev-environment

# Style Variables
brand_color: "#1188ff"

google_analytics_ua: UA-48605964-19

redcarpet:
    extensions: [with_toc_data]
