markdown: redcarpet
name: 18F Development Environment Guide
exclude:
- go
- copy-template
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md

permalink: pretty
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: People not systems
  url: people/
  internal: true
- text: Self provisioning
  url: self-provisioning/
  internal: true
- text: Automation
  url: automation/
  internal: true
- text: Environments
  url: environments/
  internal: true
- text: Update schedule
  url: updates/
  internal: true
- text: Build promotion
  url: build-promotion/
  internal: true
- text: Service contracts
  url: service-contracts/
  internal: true
- text: Continuous integration
  url: continuous-integration/
  internal: true

repos:
- name: Development Environment
  description: Main repository
  url: https://github.com/18F/dev-environment

google_analytics_ua: UA-48605964-19

redcarpet:
    extensions: [with_toc_data]

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_18f_default"
